version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    container_name: "backend"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 20s

  frontend:
    build:
      context: ./frontend
    container_name: "frontend"
    volumes:
      - frontend_build:/app/build/

  nginx:
    image: nginx:latest
    container_name: "nginx"
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/error.log:/var/log/nginx/error.log
      - frontend_build:/usr/share/nginx/html
    depends_on:
      backend:
        condition: service_started
    links:
      - "backend"

volumes:
  frontend_build: {}